# Generated by Django 5.2.8 on 2026-01-28 21:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('is_revoked', models.BooleanField(default=False, help_text='Revoke to block this license')),
                ('max_activations', models.PositiveIntegerField(default=1, help_text='Maximum simultaneous activations allowed')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for perpetual license', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this license')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(help_text='SHA256 hash of hostname (32 chars)', max_length=64)),
                ('app_version', models.CharField(max_length=20)),
                ('platform', models.CharField(help_text='win32, darwin, or linux', max_length=20)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('last_validated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='licensing.license')),
            ],
            options={
                'ordering': ['-activated_at'],
                'unique_together': {('license', 'machine_id')},
            },
        ),
    ]
